const giftsNote = [
  {
    id: 1,
    imgSrc: "./imgs/bear-toy-img.jpg",
    name: "Плюшевий ведмедик",
    category: "Для дітей",
    price: 500,
    number: 10,
  },
  {
    id: 2,
    imgSrc: "./imgs/cup-home.jpg",
    name: "Чашка з блюдцем",
    category: "Товари для дому",
    price: 400,
    number: 20,
  },
  {
    id: 21,
    imgSrc: "./imgs/camera-technology-img.jpg",
    name: "Фотоапарат",
    category: "Техніка",
    price: 1200,
    number: 210,
  },
  {
    id: 12,
    imgSrc: "./imgs/eyeshadow-woman-img.jpg",
    name: "Тіні для очей",
    category: "Для жінок",
    price: 150,
    number: 120,
  },
  {
    id: 4,
    imgSrc: "./imgs/notebook3-office-img.jpg",
    name: "Блокнот і фломастери",
    category: "Канцелярія",
    price: 230,
    number: 40,
  },
  {
    id: 5,
    imgSrc: "./imgs/cube-toy-img.jpg",
    name: "Кубик Рубіка",
    category: "Для дітей",
    price: 200,
    number: 50,
  },
  {
    id: 6,
    imgSrc: "./imgs/perfume-woman-img.jpg",
    name: "Парфуми",
    category: "Для жінок",
    price: 3000,
    number: 60,
  },
  {
    id: 10,
    imgSrc: "./imgs/Christmas-holidays-img.jpg",
    name: "Ялинкові прикраси",
    category: "Свята",
    price: 120,
    number: 100,
  },
  {
    id: 3,
    imgSrc: "./imgs/car-toy-img.jpg",
    name: "Іграшкова машинка",
    category: "Для дітей",
    price: 250,
    number: 30,
  },
  {
    id: 14,
    imgSrc: "./imgs/pendant-jewellery-img.jpg",
    name: "Срібне кольє з блакитним фіанітом",
    category: "Для жінок",
    price: 2000,
    number: 140,
  },
  {
    id: 25,
    imgSrc: "./imgs/pan-home.jpg",
    name: "Каструля",
    category: "Товари для дому",
    price: 400,
    number: 250,
  },
  {
    id: 24,
    imgSrc: "./imgs/headphone-technology-img.jpg",
    name: "Навушники",
    category: "Техніка",
    price: 850,
    number: 240,
  },
  {
    id: 30,
    imgSrc: "./imgs/stikers-office-img.jpg",
    name: "Набір зі стікерів із записничком",
    category: "Канцелярія",
    price: 80,
    number: 290,
  },
  {
    id: 8,
    imgSrc: "./imgs/mascara-woman-img.jpg",
    name: "Туш для вій",
    category: "Для жінок",
    price: 280,
    number: 80,
  },
  {
    id: 7,
    imgSrc: "./imgs/doll-toy-img.jpg",
    name: "Плюшева лялька",
    category: "Для дітей",
    price: 450,
    number: 0,
  },
  {
    id: 19,
    imgSrc: "./imgs/pencils-office-img.jpg",
    name: "Олівці",
    category: "Канцелярія",
    price: 100,
    number: 190,
  },
  {
    id: 22,
    imgSrc: "./imgs/earrings-jewellery-img.jpg",
    name: "Сережки з камінням",
    category: "Для жінок",
    price: 500,
    number: 220,
  },
  {
    id: 26,
    imgSrc: "./imgs/house-toy-img.jpg",
    name: "Ляльковий будиночок",
    category: "Для дітей",
    price: 800,
    number: 260,
  },
  {
    id: 23,
    imgSrc: "./imgs/Christmas-angel-img.jpg",
    name: "Різдвяний янгол",
    category: "Свята",
    price: 120,
    number: 230,
  },
  {
    id: 27,
    imgSrc: "./imgs/powder-woman-img.jpg",
    name: "Пудра",
    category: "Для жінок",
    price: 300,
    number: 270,
  },
  {
    id: 9,
    imgSrc: "./imgs/cologne-man.jpg",
    name: "Одеколон",
    category: "Для чоловіків",
    price: 2500,
    number: 90,
  },
  {
    id: 11,
    imgSrc: "./imgs/watch-man-img.jpg",
    name: "Чоловічий годинник",
    category: "Для чоловіків",
    price: 3000,
    number: 110,
  },
  {
    id: 29,
    imgSrc: "./imgs/notebook-office-img.jpg",
    name: "Записник з олівцем та калькулятором",
    category: "Канцелярія",
    price: 300,
    number: 290,
  },
  {
    id: 13,
    imgSrc: "./imgs/glasses-old.jpg",
    name: "Окуляри",
    category: "Для літніх людей",
    price: 1800,
    number: 0,
  },
  {
    id: 28,
    imgSrc: "./imgs/tower-home.jpg",
    name: "Набір рушників",
    category: "Товари для дому",
    price: 250,
    number: 0,
  },
  {
    id: 20,
    imgSrc: "./imgs/Christmas-balloon-img.jpg",
    name: "Снігова кулька",
    category: "Свята",
    price: 380,
    number: 200,
  },
  {
    id: 15,
    imgSrc: "./imgs/threads-old.jpg",
    name: "Набір для в'язання",
    category: "Для літніх людей",
    price: 370,
    number: 150,
  },
  {
    id: 16,
    imgSrc: "./imgs/notebook2-office-img.jpg",
    name: "Канцелярський набір",
    category: "Канцелярія",
    price: 280,
    number: 160,
  },
  {
    id: 17,
    imgSrc: "./imgs/Christmas-holidays2-img.jpg",
    name: "Набір ялинкових прикрас",
    category: "Свята",
    price: 300,
    number: 170,
  },
  {
    id: 18,
    imgSrc: "./imgs/headphone2-technology-img.jpg",
    name: "Бездротові навушники",
    category: "Техніка",
    price: 1200,
    number: 180,
  },
];

const ideasNote = [
  {
    id: 1,
    imgSrc: "./imgs/makaron-idea.jpg",
    name: "Макаруни",
    author: "Julia Divuk",
    price: 180,
    phone: "+380667833456",
    description: [
      "jhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdhjhcjsdh",
      "ndsivnsdivjhcjsdhjhcjsdh",
      "njdvkdsnvkdsfjhcjsdhn",
      "jvnvjfdnvjfdn",
      "jhcjhcjsdhjhcjsdhjhcjsdhjhcjsdhjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
    ],
  },
  {
    id: 2,
    imgSrc: "./imgs/candles-idea.jpg",
    name: "Свічки",
    author: "Anna Ravna",
    price: 100,
    phone: "+380667833456",
    description: ["jhcjsdh", "ndsivnsdiv", "njdvkdsnvkdsfn", "jvnvjfdnvjfdn"],
  },
  {
    id: 3,
    imgSrc: "./imgs/soap-idea.jpg",
    name: "Мило",
    author: "Maria Naum",
    price: 0,
    phone: "+380667833456",
    description: [
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
    ],
  },
  {
    id: 4,
    imgSrc: "./imgs/toys-idea.jpg",
    name: "М'які іграшки",
    author: "Tetiana Hnativ",
    price: 200,
    phone: "+380503388467",
    description: [
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
      "jhcjsdh",
      "ndsivnsdiv",
    ],
  },
  {
    id: 5,
    imgSrc: "./imgs/makaron-idea.jpg",
    name: "Макаруни",
    author: "Julia Divuk",
    price: 0,
    phone: "",
    description: [
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
      "jhcjsdh",
    ],
  },
  {
    id: 6,
    imgSrc: "./imgs/candles-idea.jpg",
    name: "Свічки",
    author: "Anna Ravna",
    price: 100,
    phone: "+380667833456",
    description: ["jhcjsdh", "ndsivnsdiv", "njdvkdsnvkdsfn"],
  },
  {
    id: 7,
    imgSrc: "./imgs/soap-idea.jpg",
    name: "Мило",
    author: "Maria Naum",
    price: 150,
    phone: "+380503388467",
    description: [
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
    ],
  },
  {
    id: 8,
    imgSrc: "./imgs/toys-idea.jpg",
    name: "М'які іграшки",
    author: "Tetiana Hnativ",
    price: 0,
    phone: "",
    description: [
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
      "jhcjsdh",
      "ndsivnsdiv",
      "njdvkdsnvkdsfn",
      "jvnvjfdnvjfdn",
    ],
  },
];
